const board = [
    {x:0, y:0, empty: true, solution: false},
    {x:0, y:1, empty: true, solution: false},
    {x:0, y:2, empty: true, solution: false},
    {x:0, y:3, empty: true, solution: false},
    {x:0, y:4, empty: true, solution: false},
    {x:0, y:5, empty: true, solution: false},    
    {x:1, y:0, empty: true, solution: false},
    {x:1, y:1, empty: true, solution: false},
    {x:1, y:2, empty: true, solution: false},
    {x:1, y:3, empty: true, solution: false},
    {x:1, y:4, empty: true, solution: false},
    {x:1, y:5, empty: true, solution: false},
    {x:2, y:0, empty: true, solution: false},
    {x:2, y:1, empty: true, solution: false},
    {x:2, y:2, empty: true, solution: false},
    {x:2, y:3, empty: true, solution: false},
    {x:2, y:4, empty: true, solution: false},
    {x:2, y:5, empty: true, solution: false},    
    {x:3, y:0, empty: true, solution: false},
    {x:3, y:1, empty: true, solution: false},
    {x:3, y:2, empty: true, solution: false},
    {x:3, y:3, empty: true, solution: false},
    {x:3, y:4, empty: true, solution: false},
    {x:3, y:5, empty: true, solution: false},    
    {x:4, y:0, empty: true, solution: false},
    {x:4, y:1, empty: true, solution: false},
    {x:4, y:2, empty: true, solution: false},
    {x:4, y:3, empty: true, solution: false},
    {x:4, y:4, empty: true, solution: false},     
    {x:4, y:5, empty: true, solution: false},    
    {x:5, y:0, empty: true, solution: false},
    {x:5, y:1, empty: true, solution: false},
    {x:5, y:2, empty: true, solution: false},
    {x:5, y:3, empty: true, solution: false},
    {x:5, y:4, empty: true, solution: false},      
    {x:5, y:5, empty: true, solution: false},    
]

export default board;