const board = [
    {x:0, y:0, empty: true},
    {x:0, y:1, empty: true},
    {x:0, y:2, empty: true},
    {x:0, y:3, empty: true},
    {x:0, y:4, empty: true},
    {x:1, y:0, empty: true},
    {x:1, y:1, empty: false},
    {x:1, y:2, empty: true},
    {x:1, y:3, empty: true},
    {x:1, y:4, empty: false},
    {x:2, y:0, empty: true},
    {x:2, y:1, empty: false},
    {x:2, y:2, empty: false},
    {x:2, y:3, empty: true},
    {x:2, y:4, empty: true},
    {x:3, y:0, empty: false},
    {x:3, y:1, empty: true},
    {x:3, y:2, empty: false},
    {x:3, y:3, empty: true},
    {x:3, y:4, empty: false},
    {x:4, y:0, empty: false},
    {x:4, y:1, empty: true},
    {x:4, y:2, empty: true},
    {x:4, y:3, empty: true},
    {x:4, y:4, empty: true},         
]

export default board;